apiVersion: v1
kind: ConfigMap
metadata:
  name: ubar-config
  namespace: ubar
data:
  NODE_ENV: production
  PORT: "3000"
  GATEWAY_PORT: "8080"
  TRIPS_SERVICE_PORT: "4101"
  PAYMENTS_SERVICE_PORT: "4102"
  OPS_SERVICE_PORT: "4103"
  AI_SERVICE_PORT: "4104"
  SAAS_SERVICE_PORT: "4105"
  EVENTS_SERVICE_PORT: "4106"
