apiVersion: v1
kind: Secret
metadata:
  name: ubar-secrets
  namespace: ubar
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:password@postgres.ubar.svc.cluster.local:5432/ubar
  JWT_SECRET: change-me
  METRICS_TOKEN: change-me
